In [54]:
import pandas as pd
import matplotlib.pyplot as plt 
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import seaborn as sns
from pathlib import Path
import joblib

In [55]:
pbp_DF = pd.read_csv('../datasets/props_training.csv')
pbp_DF.head()

,game_id,player_id,season,seconds_remaining,current_points,current_minutes,season_ppg,season_fga,season_mpg,fga_so_far,3pa_so_far,season_3pa,current_rebounds,season_rebounds,current_assists,season_assists,score_differential,final_points,final_rebounds,final_assists
0,22200001,203954,2022-23,2751,0,2.15,33.08,20.12,34.61,0,0,3.03,1,10.15,0,4.15,5,26,15,5
1,22200001,203954,2022-23,2689,0,3.18,33.08,20.12,34.61,0,0,3.03,2,10.15,0,4.15,7,26,15,5
2,22200001,203954,2022-23,2689,1,3.18,33.08,20.12,34.61,0,0,3.03,2,10.15,0,4.15,6,26,15,5
3,22200001,203954,2022-23,2673,1,3.45,33.08,20.12,34.61,0,0,3.03,3,10.15,0,4.15,6,26,15,5
4,22200001,203954,2022-23,2632,1,4.13,33.08,20.12,34.61,0,0,3.03,4,10.15,0,4.15,3,26,15,5

In [56]:
pbp_DF['points_remaining'] = pbp_DF['final_points'] - pbp_DF['current_points']
pbp_DF.drop(columns=['game_id', 'player_id', 'season', 'current_rebounds', 'season_rebounds', 'current_assists', 'season_assists', 'final_rebounds', 'final_assists', 'final_points'], inplace=True)
pbp_DF.drop_duplicates(inplace=True)
pbp_DF.head()

,seconds_remaining,current_points,current_minutes,season_ppg,season_fga,season_mpg,fga_so_far,3pa_so_far,season_3pa,score_differential,points_remaining
0,2751,0,2.15,33.08,20.12,34.61,0,0,3.03,5,26
1,2689,0,3.18,33.08,20.12,34.61,0,0,3.03,7,26
2,2689,1,3.18,33.08,20.12,34.61,0,0,3.03,6,25
3,2673,1,3.45,33.08,20.12,34.61,0,0,3.03,6,25
4,2632,1,4.13,33.08,20.12,34.61,0,0,3.03,3,25

In [57]:
feature_cols = ['seconds_remaining', 'current_points', 'current_minutes', 'season_ppg', 'season_fga', 'season_mpg', 'fga_so_far', '3pa_so_far', 'season_3pa', 'score_differential']
X = pbp_DF[feature_cols]
y = pbp_DF['points_remaining']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
X_tr, X_val, y_tr, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

In [58]:
model = XGBRegressor(
    objective='reg:squarederror',
    n_estimators=500,
    max_depth=7,
    learning_rate=0.1,
    subsample=0.9,
    colsample_bytree=0.9,
    random_state=42
)
model.fit(
    X_tr, y_tr,
    eval_set=[(X_val, y_val)],
    verbose=True
)

[0]	validation_0-rmse:8.91063
[1]	validation_0-rmse:8.43149
[2]	validation_0-rmse:8.02130
[3]	validation_0-rmse:7.67857
[4]	validation_0-rmse:7.37560
[5]	validation_0-rmse:7.11987
[6]	validation_0-rmse:6.90448
[7]	validation_0-rmse:6.72239
[8]	validation_0-rmse:6.57062
[9]	validation_0-rmse:6.44486
[10]	validation_0-rmse:6.34072
[11]	validation_0-rmse:6.25399
[12]	validation_0-rmse:6.18077
[13]	validation_0-rmse:6.12127
[14]	validation_0-rmse:6.07097
[15]	validation_0-rmse:6.03083
[16]	validation_0-rmse:5.99784
[17]	validation_0-rmse:5.96917
[18]	validation_0-rmse:5.94644
[19]	validation_0-rmse:5.92549
[20]	validation_0-rmse:5.90972
[21]	validation_0-rmse:5.89432
[22]	validation_0-rmse:5.88223
[23]	validation_0-rmse:5.87136
[24]	validation_0-rmse:5.86130
[25]	validation_0-rmse:5.85318
[26]	validation_0-rmse:5.84669
[27]	validation_0-rmse:5.84100
[28]	validation_0-rmse:5.83627
[29]	validation_0-rmse:5.83301
[30]	validation_0-rmse:5.82882
[31]	validation_0-rmse:5.82486
[32]	validation_0-rmse:5.82081
[33]	validation_0-rmse:5.81796
[34]	validation_0-rmse:5.81385
[35]	validation_0-rmse:5.81202
[36]	validation_0-rmse:5.80978
[37]	validation_0-rmse:5.80766
[38]	validation_0-rmse:5.80454
[39]	validation_0-rmse:5.80182
[40]	validation_0-rmse:5.79981
[41]	validation_0-rmse:5.79575
[42]	validation_0-rmse:5.79461
[43]	validation_0-rmse:5.79237
[44]	validation_0-rmse:5.78925
[45]	validation_0-rmse:5.78791
[46]	validation_0-rmse:5.78484
[47]	validation_0-rmse:5.78385
[48]	validation_0-rmse:5.78105
[49]	validation_0-rmse:5.78058
[50]	validation_0-rmse:5.77890
[51]	validation_0-rmse:5.77696
[52]	validation_0-rmse:5.77572
[53]	validation_0-rmse:5.77353
[54]	validation_0-rmse:5.77237
[55]	validation_0-rmse:5.76978
[56]	validation_0-rmse:5.76679
[57]	validation_0-rmse:5.76554
[58]	validation_0-rmse:5.76327
[59]	validation_0-rmse:5.76126
[60]	validation_0-rmse:5.76040
[61]	validation_0-rmse:5.76018
[62]	validation_0-rmse:5.75852
[63]	validation_0-rmse:5.75690
[64]	validation_0-rmse:5.75580
[65]	validation_0-rmse:5.75541
[66]	validation_0-rmse:5.75454
[67]	validation_0-rmse:5.75384
[68]	validation_0-rmse:5.75448
[69]	validation_0-rmse:5.75256
[70]	validation_0-rmse:5.75171
[71]	validation_0-rmse:5.75121
[72]	validation_0-rmse:5.75107
[73]	validation_0-rmse:5.74990
[74]	validation_0-rmse:5.74844
[75]	validation_0-rmse:5.74647
[76]	validation_0-rmse:5.74625
[77]	validation_0-rmse:5.74514
[78]	validation_0-rmse:5.74357
[79]	validation_0-rmse:5.74265
[80]	validation_0-rmse:5.74284
[81]	validation_0-rmse:5.74289
[82]	validation_0-rmse:5.74094
[83]	validation_0-rmse:5.73899
[84]	validation_0-rmse:5.73791
[85]	validation_0-rmse:5.73631
[86]	validation_0-rmse:5.73507
[87]	validation_0-rmse:5.73508
[88]	validation_0-rmse:5.73318
[89]	validation_0-rmse:5.73260
[90]	validation_0-rmse:5.73062
[91]	validation_0-rmse:5.73019
[92]	validation_0-rmse:5.72987
[93]	validation_0-rmse:5.72853
[94]	validation_0-rmse:5.72757
[95]	validation_0-rmse:5.72762
[96]	validation_0-rmse:5.72772
[97]	validation_0-rmse:5.72710
[98]	validation_0-rmse:5.72613
[99]	validation_0-rmse:5.72511
[100]	validation_0-rmse:5.72337
[101]	validation_0-rmse:5.72272
[102]	validation_0-rmse:5.72165
[103]	validation_0-rmse:5.72097
[104]	validation_0-rmse:5.72091
[105]	validation_0-rmse:5.72107
[106]	validation_0-rmse:5.72031
[107]	validation_0-rmse:5.71866
[108]	validation_0-rmse:5.71782
[109]	validation_0-rmse:5.71588
[110]	validation_0-rmse:5.71478
[111]	validation_0-rmse:5.71448
[112]	validation_0-rmse:5.71397
[113]	validation_0-rmse:5.71230
[114]	validation_0-rmse:5.71137
[115]	validation_0-rmse:5.71144
[116]	validation_0-rmse:5.71082
[117]	validation_0-rmse:5.71053
[118]	validation_0-rmse:5.70937
[119]	validation_0-rmse:5.70921
[120]	validation_0-rmse:5.71006
[121]	validation_0-rmse:5.70913
[122]	validation_0-rmse:5.70911
[123]	validation_0-rmse:5.70748
[124]	validation_0-rmse:5.70763
[125]	validation_0-rmse:5.70724
[126]	validation_0-rmse:5.70631
[127]	validation_0-rmse:5.70589
[128]	validation_0-rmse:5.70452
[129]	validation_0-rmse:5.70432
[130]	validation_0-rmse:5.70534
[131]	validation_0-rmse:5.70530
[132]	validation_0-rmse:5.70394
[133]	validation_0-rmse:5.70300
[134]	validation_0-rmse:5.70256
[135]	validation_0-rmse:5.70220
[136]	validation_0-rmse:5.70139
[137]	validation_0-rmse:5.70015
[138]	validation_0-rmse:5.69880
[139]	validation_0-rmse:5.69894
[140]	validation_0-rmse:5.69726
[141]	validation_0-rmse:5.69729
[142]	validation_0-rmse:5.69756
[143]	validation_0-rmse:5.69759
[144]	validation_0-rmse:5.69740
[145]	validation_0-rmse:5.69600
[146]	validation_0-rmse:5.69535
[147]	validation_0-rmse:5.69542
[148]	validation_0-rmse:5.69531
[149]	validation_0-rmse:5.69481
[150]	validation_0-rmse:5.69452
[151]	validation_0-rmse:5.69428
[152]	validation_0-rmse:5.69382
[153]	validation_0-rmse:5.69362
[154]	validation_0-rmse:5.69322
[155]	validation_0-rmse:5.69204
[156]	validation_0-rmse:5.69062
[157]	validation_0-rmse:5.69048
[158]	validation_0-rmse:5.68911
[159]	validation_0-rmse:5.68851
[160]	validation_0-rmse:5.68764
[161]	validation_0-rmse:5.68707
[162]	validation_0-rmse:5.68613
[163]	validation_0-rmse:5.68578
[164]	validation_0-rmse:5.68533
[165]	validation_0-rmse:5.68497
[166]	validation_0-rmse:5.68299
[167]	validation_0-rmse:5.68237
[168]	validation_0-rmse:5.68258
[169]	validation_0-rmse:5.68224
[170]	validation_0-rmse:5.68228
[171]	validation_0-rmse:5.68212
[172]	validation_0-rmse:5.68132
[173]	validation_0-rmse:5.68142
[174]	validation_0-rmse:5.68093
[175]	validation_0-rmse:5.68058
[176]	validation_0-rmse:5.67999
[177]	validation_0-rmse:5.67866
[178]	validation_0-rmse:5.67839
[179]	validation_0-rmse:5.67771
[180]	validation_0-rmse:5.67681
[181]	validation_0-rmse:5.67665
[182]	validation_0-rmse:5.67658
[183]	validation_0-rmse:5.67652
[184]	validation_0-rmse:5.67495
[185]	validation_0-rmse:5.67460
[186]	validation_0-rmse:5.67357
[187]	validation_0-rmse:5.67300
[188]	validation_0-rmse:5.67318
[189]	validation_0-rmse:5.67189
[190]	validation_0-rmse:5.67142
[191]	validation_0-rmse:5.67090
[192]	validation_0-rmse:5.66988
[193]	validation_0-rmse:5.67005
[194]	validation_0-rmse:5.66954
[195]	validation_0-rmse:5.66993
[196]	validation_0-rmse:5.66936
[197]	validation_0-rmse:5.66862
[198]	validation_0-rmse:5.66848
[199]	validation_0-rmse:5.66841
[200]	validation_0-rmse:5.66810
[201]	validation_0-rmse:5.66786
[202]	validation_0-rmse:5.66755
[203]	validation_0-rmse:5.66663
[204]	validation_0-rmse:5.66736
[205]	validation_0-rmse:5.66787
[206]	validation_0-rmse:5.66785
[207]	validation_0-rmse:5.66815
[208]	validation_0-rmse:5.66835
[209]	validation_0-rmse:5.66821
[210]	validation_0-rmse:5.66696
[211]	validation_0-rmse:5.66599
[212]	validation_0-rmse:5.66565
[213]	validation_0-rmse:5.66492
[214]	validation_0-rmse:5.66486
[215]	validation_0-rmse:5.66379
[216]	validation_0-rmse:5.66298
[217]	validation_0-rmse:5.66308
[218]	validation_0-rmse:5.66298
[219]	validation_0-rmse:5.66207
[220]	validation_0-rmse:5.66207
[221]	validation_0-rmse:5.66175
[222]	validation_0-rmse:5.66016
[223]	validation_0-rmse:5.65997
[224]	validation_0-rmse:5.65976
[225]	validation_0-rmse:5.65883
[226]	validation_0-rmse:5.65932
[227]	validation_0-rmse:5.65922
[228]	validation_0-rmse:5.65904
[229]	validation_0-rmse:5.65916
[230]	validation_0-rmse:5.65902
[231]	validation_0-rmse:5.65926
[232]	validation_0-rmse:5.65884
[233]	validation_0-rmse:5.65852
[234]	validation_0-rmse:5.65815
[235]	validation_0-rmse:5.65807
[236]	validation_0-rmse:5.65716
[237]	validation_0-rmse:5.65737
[238]	validation_0-rmse:5.65775
[239]	validation_0-rmse:5.65798
[240]	validation_0-rmse:5.65772
[241]	validation_0-rmse:5.65798
[242]	validation_0-rmse:5.65833
[243]	validation_0-rmse:5.65788
[244]	validation_0-rmse:5.65794
[245]	validation_0-rmse:5.65794
[246]	validation_0-rmse:5.65801
[247]	validation_0-rmse:5.65876
[248]	validation_0-rmse:5.65844
[249]	validation_0-rmse:5.65828
[250]	validation_0-rmse:5.65790
[251]	validation_0-rmse:5.65735
[252]	validation_0-rmse:5.65687
[253]	validation_0-rmse:5.65697
[254]	validation_0-rmse:5.65650
[255]	validation_0-rmse:5.65725
[256]	validation_0-rmse:5.65659
[257]	validation_0-rmse:5.65594
[258]	validation_0-rmse:5.65531
[259]	validation_0-rmse:5.65481
[260]	validation_0-rmse:5.65464
[261]	validation_0-rmse:5.65424
[262]	validation_0-rmse:5.65327
[263]	validation_0-rmse:5.65333
[264]	validation_0-rmse:5.65365
[265]	validation_0-rmse:5.65408
[266]	validation_0-rmse:5.65278
[267]	validation_0-rmse:5.65273
[268]	validation_0-rmse:5.65227
[269]	validation_0-rmse:5.65138
[270]	validation_0-rmse:5.64981
[271]	validation_0-rmse:5.64974
[272]	validation_0-rmse:5.64959
[273]	validation_0-rmse:5.64922
[274]	validation_0-rmse:5.64905
[275]	validation_0-rmse:5.64870
[276]	validation_0-rmse:5.64825
[277]	validation_0-rmse:5.64722
[278]	validation_0-rmse:5.64659
[279]	validation_0-rmse:5.64662
[280]	validation_0-rmse:5.64619
[281]	validation_0-rmse:5.64570
[282]	validation_0-rmse:5.64531
[283]	validation_0-rmse:5.64570
[284]	validation_0-rmse:5.64523
[285]	validation_0-rmse:5.64506
[286]	validation_0-rmse:5.64460
[287]	validation_0-rmse:5.64462
[288]	validation_0-rmse:5.64373
[289]	validation_0-rmse:5.64323
[290]	validation_0-rmse:5.64258
[291]	validation_0-rmse:5.64225
[292]	validation_0-rmse:5.64227
[293]	validation_0-rmse:5.64170
[294]	validation_0-rmse:5.64083
[295]	validation_0-rmse:5.64041
[296]	validation_0-rmse:5.64018
[297]	validation_0-rmse:5.63965
[298]	validation_0-rmse:5.63949
[299]	validation_0-rmse:5.63772
[300]	validation_0-rmse:5.63698
[301]	validation_0-rmse:5.63762
[302]	validation_0-rmse:5.63723
[303]	validation_0-rmse:5.63774
[304]	validation_0-rmse:5.63795
[305]	validation_0-rmse:5.63762
[306]	validation_0-rmse:5.63749
[307]	validation_0-rmse:5.63804
[308]	validation_0-rmse:5.63739
[309]	validation_0-rmse:5.63774
[310]	validation_0-rmse:5.63706
[311]	validation_0-rmse:5.63678
[312]	validation_0-rmse:5.63673
[313]	validation_0-rmse:5.63633
[314]	validation_0-rmse:5.63618
[315]	validation_0-rmse:5.63611
[316]	validation_0-rmse:5.63648
[317]	validation_0-rmse:5.63612
[318]	validation_0-rmse:5.63543
[319]	validation_0-rmse:5.63504
[320]	validation_0-rmse:5.63407
[321]	validation_0-rmse:5.63376
[322]	validation_0-rmse:5.63370
[323]	validation_0-rmse:5.63310
[324]	validation_0-rmse:5.63319
[325]	validation_0-rmse:5.63276
[326]	validation_0-rmse:5.63237
[327]	validation_0-rmse:5.63196
[328]	validation_0-rmse:5.63194
[329]	validation_0-rmse:5.63187
[330]	validation_0-rmse:5.63229
[331]	validation_0-rmse:5.63272
[332]	validation_0-rmse:5.63271
[333]	validation_0-rmse:5.63216
[334]	validation_0-rmse:5.63179
[335]	validation_0-rmse:5.63165
[336]	validation_0-rmse:5.63161
[337]	validation_0-rmse:5.63204
[338]	validation_0-rmse:5.63139
[339]	validation_0-rmse:5.63182
[340]	validation_0-rmse:5.63157
[341]	validation_0-rmse:5.63097
[342]	validation_0-rmse:5.63106
[343]	validation_0-rmse:5.63110
[344]	validation_0-rmse:5.63070
[345]	validation_0-rmse:5.63040
[346]	validation_0-rmse:5.62917
[347]	validation_0-rmse:5.62854
[348]	validation_0-rmse:5.62836
[349]	validation_0-rmse:5.62774
[350]	validation_0-rmse:5.62715
[351]	validation_0-rmse:5.62703
[352]	validation_0-rmse:5.62769
[353]	validation_0-rmse:5.62712
[354]	validation_0-rmse:5.62619
[355]	validation_0-rmse:5.62625
[356]	validation_0-rmse:5.62633
[357]	validation_0-rmse:5.62624
[358]	validation_0-rmse:5.62581
[359]	validation_0-rmse:5.62499
[360]	validation_0-rmse:5.62574
[361]	validation_0-rmse:5.62569
[362]	validation_0-rmse:5.62570
[363]	validation_0-rmse:5.62581
[364]	validation_0-rmse:5.62576
[365]	validation_0-rmse:5.62575
[366]	validation_0-rmse:5.62531
[367]	validation_0-rmse:5.62554
[368]	validation_0-rmse:5.62563
[369]	validation_0-rmse:5.62488
[370]	validation_0-rmse:5.62533
[371]	validation_0-rmse:5.62584
[372]	validation_0-rmse:5.62561
[373]	validation_0-rmse:5.62565
[374]	validation_0-rmse:5.62508
[375]	validation_0-rmse:5.62473
[376]	validation_0-rmse:5.62460
[377]	validation_0-rmse:5.62458
[378]	validation_0-rmse:5.62521
[379]	validation_0-rmse:5.62546
[380]	validation_0-rmse:5.62560
[381]	validation_0-rmse:5.62549
[382]	validation_0-rmse:5.62527
[383]	validation_0-rmse:5.62549
[384]	validation_0-rmse:5.62504
[385]	validation_0-rmse:5.62474
[386]	validation_0-rmse:5.62464
[387]	validation_0-rmse:5.62479
[388]	validation_0-rmse:5.62425
[389]	validation_0-rmse:5.62360
[390]	validation_0-rmse:5.62336
[391]	validation_0-rmse:5.62341
[392]	validation_0-rmse:5.62298
[393]	validation_0-rmse:5.62316
[394]	validation_0-rmse:5.62289
[395]	validation_0-rmse:5.62211
[396]	validation_0-rmse:5.62217
[397]	validation_0-rmse:5.62138
[398]	validation_0-rmse:5.62132
[399]	validation_0-rmse:5.62177
[400]	validation_0-rmse:5.62124
[401]	validation_0-rmse:5.62113
[402]	validation_0-rmse:5.62123
[403]	validation_0-rmse:5.62048
[404]	validation_0-rmse:5.61944
[405]	validation_0-rmse:5.61989
[406]	validation_0-rmse:5.62024
[407]	validation_0-rmse:5.62002
[408]	validation_0-rmse:5.62015
[409]	validation_0-rmse:5.62076
[410]	validation_0-rmse:5.62041
[411]	validation_0-rmse:5.62091
[412]	validation_0-rmse:5.62110
[413]	validation_0-rmse:5.62160
[414]	validation_0-rmse:5.62134
[415]	validation_0-rmse:5.62105
[416]	validation_0-rmse:5.62174
[417]	validation_0-rmse:5.62151
[418]	validation_0-rmse:5.62132
[419]	validation_0-rmse:5.62173
[420]	validation_0-rmse:5.62137
[421]	validation_0-rmse:5.62108
[422]	validation_0-rmse:5.62129
[423]	validation_0-rmse:5.62122
[424]	validation_0-rmse:5.62135
[425]	validation_0-rmse:5.62097
[426]	validation_0-rmse:5.62129
[427]	validation_0-rmse:5.62131
[428]	validation_0-rmse:5.62052
[429]	validation_0-rmse:5.62050
[430]	validation_0-rmse:5.62136
[431]	validation_0-rmse:5.62089
[432]	validation_0-rmse:5.62098
[433]	validation_0-rmse:5.62122
[434]	validation_0-rmse:5.62122
[435]	validation_0-rmse:5.62131
[436]	validation_0-rmse:5.62056
[437]	validation_0-rmse:5.62055
[438]	validation_0-rmse:5.62080
[439]	validation_0-rmse:5.62068
[440]	validation_0-rmse:5.62084
[441]	validation_0-rmse:5.62064
[442]	validation_0-rmse:5.61997
[443]	validation_0-rmse:5.61982
[444]	validation_0-rmse:5.61956
[445]	validation_0-rmse:5.61998
[446]	validation_0-rmse:5.61933
[447]	validation_0-rmse:5.61930
[448]	validation_0-rmse:5.61946
[449]	validation_0-rmse:5.61895
[450]	validation_0-rmse:5.61907
[451]	validation_0-rmse:5.61865
[452]	validation_0-rmse:5.61853
[453]	validation_0-rmse:5.61849
[454]	validation_0-rmse:5.61816
[455]	validation_0-rmse:5.61760
[456]	validation_0-rmse:5.61716
[457]	validation_0-rmse:5.61713
[458]	validation_0-rmse:5.61650
[459]	validation_0-rmse:5.61657
[460]	validation_0-rmse:5.61640
[461]	validation_0-rmse:5.61585
[462]	validation_0-rmse:5.61604
[463]	validation_0-rmse:5.61580
[464]	validation_0-rmse:5.61579
[465]	validation_0-rmse:5.61539
[466]	validation_0-rmse:5.61545
[467]	validation_0-rmse:5.61566
[468]	validation_0-rmse:5.61553
[469]	validation_0-rmse:5.61462
[470]	validation_0-rmse:5.61451
[471]	validation_0-rmse:5.61391
[472]	validation_0-rmse:5.61425
[473]	validation_0-rmse:5.61383
[474]	validation_0-rmse:5.61404
[475]	validation_0-rmse:5.61440
[476]	validation_0-rmse:5.61417
[477]	validation_0-rmse:5.61423
[478]	validation_0-rmse:5.61401
[479]	validation_0-rmse:5.61444
[480]	validation_0-rmse:5.61441
[481]	validation_0-rmse:5.61439
[482]	validation_0-rmse:5.61469
[483]	validation_0-rmse:5.61460
[484]	validation_0-rmse:5.61436
[485]	validation_0-rmse:5.61413
[486]	validation_0-rmse:5.61423
[487]	validation_0-rmse:5.61438
[488]	validation_0-rmse:5.61431
[489]	validation_0-rmse:5.61364
[490]	validation_0-rmse:5.61346
[491]	validation_0-rmse:5.61276
[492]	validation_0-rmse:5.61273
[493]	validation_0-rmse:5.61279
[494]	validation_0-rmse:5.61249
[495]	validation_0-rmse:5.61294
[496]	validation_0-rmse:5.61236
[497]	validation_0-rmse:5.61222
[498]	validation_0-rmse:5.61254
[499]	validation_0-rmse:5.61261

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.9, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=7,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=500,
             n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
def eval_model():
    y_pred = model.predict(X_test)
    mae = mean_absolute_error(y_test, y_pred)
    rmse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    print(f"MAE: {mae:.2f}")
    print(f"RMSE: {rmse:.2f}")
    print(f"R²: {r2:.3f}")

def custom_predictions(custom_data):
    # index=[0] required when custom_data is a dict of scalars (one row)
    custom_df = pd.DataFrame(custom_data, index=[0])
    custom_df = custom_df[['seconds_remaining', 'current_points', 'current_minutes', 'season_ppg', 'season_fga', 'season_mpg', 'fga_so_far', '3pa_so_far', 'season_3pa', 'score_differential']]
    points_remaining = round(model.predict(custom_df)[0])
    points_started = custom_data['current_points']
    print(f"Points started with: {points_started}")
    print(f"Points predicted left to score: {points_remaining}")
    print(f"Final points: {points_started + points_remaining}")

def save_model(model, model_path_name):
    model_path = Path(model_path_name)
    joblib.dump(model, model_path)
    print(f"Model saved to {model_path.absolute()}")

In [60]:
eval_model()

MAE: 4.19
RMSE: 32.57
R²: 0.642

In [65]:
custom_data = {
    'seconds_remaining': 720,
    'current_points': 18,
    'current_minutes': 24,
    'season_ppg': 27,
    'season_fga': 19,
    'season_mpg': 36,
    'fga_so_far': 14,
    '3pa_so_far': 8,
    'season_3pa': 10,
    'score_differential': 2,
}

custom_predictions(custom_data)

Points started with: 18
Points predicted left to score: 7
Final points: 25

In [ ]:
save_model(model, 'pts_model.joblib')